<?php

//Content common to all pages

$messages = [
"page_title" => "Manage Activities",

"psel" => "Please Select",

"recent" => "recent activities",
"recent_sub" => "these are the activities that you may be interested in.",
"suggested_activities" => "suggested activities",
"activity_name" => "activity name",
//Schools content

#schools dashboard page starts here
"activities" =>"Your Activities",

"activities_sub" =>"Welcome to your activities page. Below you will find the activities you have stored with us. You can add more or edit the ones you already have. These are the foundation of your lesson plan so be sure to provide as much detail as possible.",

#panels
"pan1_cnt_head" =>"Activities",
"pan1_cnt_sub" =>"Added to your account.",

"pan2_cnt_head" =>"Lessn Plans",
"pan2_cnt_sub" =>"That have no activities.",
"psel" => "Please Select...",
"button" =>"add a new activity",

#schools management page starts here.
"title" =>"Manage Classes",

"update_head" =>"Update an Activity",
"update_txt" =>"Please update the details as you need to.",
"update_head_sub" =>"<small> keepin' it <strong>real</strong>, like it should be.</small>",

"table_head" =>"Activities",
"table_sub" =>"This is a list of the activities that you have stored on eigomonstar.com. You can update these as you need to. Updating activities will automatically update them in the lesson plans that your teaching. If you want to create a variation, copy the activity and then edit that.",

"create_head" =>"Create and Activity",
"create_head_txt" =>"Please fill the details to create a new activity. They will be available to you when you start planning lessons.",
"create_head_sub" =>"<small> make sure the monstar are <strong>need</strong> enageged </small>",

"table_head" =>"Activities",
"table_sub" =>"These are the activities you have stored. REMEMBER: editing an activity already used in a lesson plan will change the activity in that lesson plan too. You should <strong>COPY</strong> an activity first before editing it.",

#start headings for the form
"step1" =>"Activity Name",
"step2" =>"Details",
"step3" =>"Setup",
"step4" =>"Materials",
"step5" =>"Steps",
"act_type" => "Type:",
"act_abil" => "Teacher's Ability:",
"act_name" =>"Activity Name:",
"act_name_help" =>"Give your activity a cool name. This will appear in the searches when you look for it.",
"act_lang" =>"Target Language:",
"act_lang_help" =>"The specific target language or grammar point that this activity is designed to teach.",
"act_summ" =>"Short Summary:",
"act_summ_help" =>"A brief guiding summary of what his activity is designed to do.",
"act_desc" =>"Detailed Description",
"act_desc_help" =>"This is to help others run this activity. Think \"general hints and tips\".",
"act_obj" =>"Objective",
"act_obj_help" =>"What is this activity designed to achieve. You can select more than one objective.",
"act_time" =>"Time",
"act_time_help" =>"How long will this activity run for?",
"act_stu_min_help" =>"The minimum number of students required to run this activity.",
"act_stu_min" =>"Students (min)",
"act_stu_max" =>"Students (max)",
"act_stu_max_help" =>"The maximum number of students this activity would be good for.",
"act_stu_type" =>"Student Type",
"act_stu_type_help" =>"The kind of students that this activity would work well for. You can select more than one.",
"act_tags" =>"Tags",
"act_tags_help" =>"Tags to help you associate this activity with lesson plans and materials",
"act_level" =>"Target Level",
"act_level_help" =>"The target level for this activity.",
"act_grade" =>"Target Grade",
"act_grade_help" =>"The grade for which this activity is geared for",
"act_team" =>"Team Teaching Style",
"act_team_help" =>"Who will be teaching this activity.",
"act_text" =>"Text Books",
"act_text_help" =>"The text book that this activity relates to",
"act_cres" =>"Kids Resources",
"act_cres_help" =>"The resources that this activity needs present in the classroom.",
"act_sres" =>"Classroom Resources",
"act_sres_help" =>"The things the kids need to have to be able to complete this activity.",
"act_subject" =>"Subject",
"act_subject_help" =>"The subject for which this activity is for.",
"act_other" =>"Other things",
"act_other_help" =>"Any special requests that this activity may have.",
"step1_sub" =>" - an overview of your activity.",
"step1_explain" =>"This is general information about the activity. This will appear in the searches and on your activities dashboard. The <strong>DESCRIPTION</strong> is for hints and tips. You will add detailed <strong>STEPS</strong> under the 5th section.",
"step2_sub" =>" - it is all in the detail.",
"step2_explain" =>"These are important details for your activity. When you add the activity to a lesson plan, these will automatically be pulled through so that you know how many of everything you need to bring for example.",
"step3_sub" =>" - what you need to be successful.",
"step3_explain" =>"These are the resources that the classroom needs to have as well as the things the students need to bring. This will help you teaching partner know what to prepare for.",
"step4_sub" =>" - keep the learners engaged.",
"step4_explain" =>"These are the materials that are required to be brought by you or the HRT to teach the lesson. You should have added these by now to your profile. If not, you can go back and add them then come back and complete this activity.",
"step5_sub" =>" - a blow by blow guide of how to run this activity.",
"step5_explain" =>"This is the most important part of the activity. Break it down into simple, easy to understand steps so that someone you cannot speak to can read and understand. Keep it simple and be descriptive e.g. SAY: Stand up please. Hands up please. Let's Begin!",
"steps_adder" =>"Add steps",
"steps_adder_up" =>"Update steps",
"steps_adder_sub" =>"Add a new step to this activity.",
"steps_adder_up_sub" =>"Update this step in this activity.",
"steps_adder_name" =>"Step Name",
"steps_adder_name_place" =>"Step Name",
"steps_adder_desc" =>"Description",
"steps_adder_place" =>"Add steps to this activity.",
"steps_adder_say_place" =>"What to say or do.",
"steps_adder_desc_place" =>"What needs to be done?",
"steps_adder_button" =>"Add Step",
"steps_sub" =>"Add Material",
"steps_sub_sub" =>"Add Material",
"steps_sub_explain" =>"To add a material, simply select it from this list and click the add material button.",
"steps_sub_button" =>"Add Material",
"steps_sub_email" =>"Email",
"steps_header" =>"Activity details",

"act_cmats" =>"Current Materials",
"act_cmats_sub" =>"These are the materials you have added to this activity. You can add more as you need to. They will automatically be added to your lesson plan",

"save_activity" => "save activity",
"next" =>"Next",
"previous" => "Previous",
"add_material" => "add material",
"show" => "Show the students",
"tell" => "Tell the students",
"step" => "Step information",
"vital" => "vital",
"edit_step" => "Edit Step",
"step_name" => "Step Name",
"steps_crucial" => "Crucial",
"step_image" => "Image",
"edit_step_text"=>"You can edit this step by changing the details below.",
"close"=>"close",
"save"=>"save",
"no_records_found"=>" no records found",
"no_objectives_added" => "no objectives added",
"suggest" => "suggest",
"delete"=>"reply",
"reply"=>"reply",
"comment"=>"comment",
"likes"=>"like",
"contributors"=>"contributors",
"add_user"=>"add user",
"no_contributors"=>"no contributors added",
"objectives"=>"objectives",
"no_steps_added"=>"no steps added",
"materials"=>"materials",
"no_materials_added"=>"no_materials added",
"add_plan" => "add a lesson plan",
"add_plan_sub" => "you can add a lesson plan to this discussion to help guide it.",
"select_plan" => "select a plan",
"mod_close" => "close",
"mod_save" => "save",
"add_activity" => "add activity",
"add_activity_sub" => "you can add an activity to this discussion to help guide it.",
"select_activity" => "select activity",
"add_material" => "add material",
"add_material_sub" => "you can add a material set to this discussion to help guide it.",
"select_material" => "select material",
"sg_activity"=>"activity",
"sg_materials"=>"material",
"sg_lessonplan"=>"lesson plan",
"plan_comment"=>"post",
"poster_placeholder"=>"give some great advice...",
"save_class"=>"Save Class",
"add_new_class"=>"add new class",
"save_as_new" => "save new",
"add_new" => "add new",
"save" => "save",
"school_level" => "school level",
"posted_status" => "posted",
"write_placeholder" => "comment like a commando",
"suggested_label" => "suggested",
"sug_plan_txt" => "lesson plan",
"sug_activity_txt" => "activity",
"sug_material_txt" => "material",
"steps_type" => "Step Type",
"steps_adder_say" => "What to do or say"


]
?>