<?php

// app/messages/en.php
$messages = [
	"psel" => "please select",
	"page_title"    => "create materials",
	"associate_textbook" => "associate textbook",
	"avaiable_words" => "available words",
	"manage_options" => "manage options",
	"structure" => "structure",
    "act_text"      => "textbook",
    "act_text"     => "please select a text book from which to generate content.",
	"txt_page" => "please select the page from which you would like to generate text.",
    "add_words" => "add words",
	"no_words_found" => "no words were found for this page in the text book.",
	"gen_words" => "generate words",
    "clear_words"    => "clear all words",
	"gen_subj" => "subject",
	"gen_name"     => "name",
	"gen_name_help" => "please enter a name for your. this will not be displayed.",
	"gen_head"     => "heading",
	"gen_head_help"     => "please enter a header for this generator. this will not be displayed.",
	"gen_subtext"     => "sub header",
	"gen_subtext_help"     => "please enter a subheading for your generator. this will not be displayed.",
	"show_name"     => "name box",
	"show_name_help"     => "please enter the text to display where students will enter their name on your generated material.",
	"show_class"     => "class box",
	"show_class_help"     => "please enter the text to display where students will enter their class on your generated material.",
	"show_date"     => "date box",
	"show_date_help"     => "please enter the text to display where students will enter the date on your generated material.",
	"show_name_check"     => "show name",
	"show_name_check_help"     => "show name box on generated materials?",
	"show_class_check" => "show class",
	"show_class_check_help" => "show class box on generated materials?",
	"show_date_check" => "show date",
	"show_date_check_help" => "show date box on generated materials?",
	"gen_desc"     => "description",
	"gen_desc_help" => "a description to help other users understand your generator. This will not be shown on the generated materials.",
	"save_and_print" => "save and print",
	"view" => "view",
	"download" => "download",
	"save_as_new" => "save as new",
	"save" => "save",
	"add_new" => "add new",
	"save_options" => "save options",
	"remove_vowels" => "remove vowels",
	"shuffle_vowels" => "shuffle vowels",
	"shuffle word" => "shuffle word",
	"subtext_word" => "subtext",
	"save_block" => "save block",
	"activities" => "generated materials list",
	"activities_sub" => "This is a list of all the materials that you have generated using eigomonster.",
	"recent" => "recently added",
	"recent_sub" => "these are some of the generated materials recently added to the system.",
	"suggested_generators" => "you can copy these to your profile and edit them.",
	"gen_count" => "Copies"
	

	
];


