<?php

//Content common to all pages

// app/messages/en.php
$messages = [
"page_title" => "Manage Schedule",
"your_schedule" => "your schedule",
"your_schedule_sub" => "From here you can manage where and when you are teaching. Simply drag classes from the left hand panel into the calendar. You can switch between day and time to view a more precise time line.",
"add_event" => "add event...",
"drag_events" => "Drag Events to Calendar Dates",
"manage_class" => "manage a class",
"manage_class_sub" => "These are the details relating to this class. You can add a lesson plan to this class from here too.",
"lesson_theme" => "lesson theme",
"lesson_plan" => "lesson plan",
"lesson_plan_help" => "The lesson plan you want to use or have used.",
"lesson_materials" => "lesson materials",
"lesson_materials_help" => "Any materials you may have used or want to use during this class.",
"activities" => "activities",
"activities_help" => "Any activities you may have used or want to use during this class.",
"comment" => "comment",
"comment_help" => "Use this to add notes about this class and how it went or what you want to achieve. You can add more details in the comments section of the main view for this schedule entry.",
"delete_lesson" => "Delete Lesson",
"update_lesson" => "Update Lesson",
"missing_sch_resources" => "missing school resources",
"missing_kids_resources" => "missing kids resources",
"change_plan" => "change plan",
"add_plan" => "add plan",
"add_user" => "add user",
"poster_placeholder" => "add some awesome....",
"plan_comment" => "post",
"add_activity" => "add activity",
"add_material" => "add material",
"add_lessonplan" => "add lesson plan",
"psel" => "please select",
"no_lesson_plan" => "There is currently no lesson plan for this lesson. Please add one.",
"no_theme_assigned" => "Please add a theme to this lesson. This will help us find lesson plans for you.",
"no_contributors" => "there are no contributors to help you plan. add a few to help the lesson planning process.",
"no_theme_added" => "What you are teaching is important. Add a lesson plan theme to help you as you decide on the contents of your lesson.",
"add_activity_sub" => "You can suggest an activity to help with the planning process. Select one from your activities and hit save.",
"mod_close" => "close",
"mod_save" => "save",
"suggested_label" => "suggested",
"sug_plan_txt" => "lesson plan",
"sug_activity_txt" => "activity",
"sug_material_txt" => "material",
"search" => "search",
"teach_rating" => "teacher rating",
"class_rating" => "class rating",
"materials" => "materials",
"no_data_found" => "We were not able to find any data for your search. Have you updated your schedule lately?",
"click_to_change" => "click to change date range",
"rating_on_or_off" => "If you do not want the system to calculate the rating you can turn this off.",
"sch_tags" => "Schedule Tags",
"sch_tags_help" => "You can add tags to this to help you summarize your class.",
"no_activities_added" => "no activities added to this section",
"add_plan_sub" => "Add a plan to this lesson so that we can help you create a great learning experience for your students on this day.",
"select_plan" => "Select a plan ",
"lp_subj" => "Subject",
"repeating_info" => "You can auto schedule this class using the fields below. This will allow you to schedule the class ahead for up to a year.",
"frequency" => "frequency",
"weekly" => "weekly",
"biweekly" => "biweekly",
"twoweeks" => "two weeks",
"threemonth" => "three months",
"halfyear" => "half year",
"monthly" => "monthly",
"schedule_ahead" => "Schedule Ahead",
"twoweeks" => "two weeks",
"onemonth" => "one month",
"oneyear" => "one year",
"occurences" => "occurences",
"auto_schedule" => "auto schedule",
"planning"=>"planning",
"evaluation"=>"evaluation",
"occurs"=>"number of times",
"repeating_edit_info"=>"You can use the following buttons below to edit this series. This operation cannot be undone so use with care. Any associated information will be deleted too.",
"del_all"=>"Delete Entire Series",


];

?>