<?php


$messages =[
"page_title" => "Manage Schools",
"psel" => "Please Select...",
"schools" => "Your Schools",
"schools_sub" => "Welcome to your schools page. Below you will find the schools you have stored here. You can add more or edit the ones you already have.<br><br>This is also where you can keep track of who you teach with and where to send lesson plan notifications to. ",
"schools_cnt_head" => "Schools",
"schools_cnt_sub" => "Added to your account.",
"classes_cnt_head" => "Classes",
"classes_cnt_sub" => "Total in all your schools.",
"button" => "add a new school.",
"title" => "Manage Schools",
"update_head" => "Update a School",
"update_txt" => "Please update the details as you need to. Remember that updating these details will update the information site wide including all your lesson plans that you have shared with others.",
"update_head_sub" => "<small> keepin' it <strong>real</strong>, like it should be.</small>",
"create_head" => "Create a School",
"create_head_txt" => "Please fill in the details to create a new school. If you need to get the address and other details, you can head to schools website and grab what you need to. These details are important so that we can, for example, send free materials to your school, help put directions into your schedule etc.",
"create_head_sub" => "<small> know where you <strong>need</strong> to be.</small>",
"overview" => "Overview",
"address_details" => "Address Details",
"contact_details" => "Contact Details",
"resources" => "Resources",
"school_name" => "School Name:",
"japanese_name" => "Japanese Name:",
"sel_level" => "School Level:",
"sel_color" => "Schedule Color:",
"sch_desc" => "School Description:",
"add_explain" => "You can have your materials delivered to your school to save you having to cart them around. You can find all the information you need on the schools website.",
"add1" => "Address Line 1:",
"add2" => "Address Line 2:",
"add3" => "Address Line 3:",
"pcode" => "Postal Code:",
"prefecture" => "Prefecture:",
"city" => "City",
"next" => "Next:",
"previous" => "Previous:",
"contact_details" => "Contact Details:",
"con_explain" => "It is always handy to have these in case of emergency. You can find the detail you need on your schools website.You can also download this questionnarie and give it to your teaching partner to fill out.",
"telno" => "Telephone Number:",
"faxno" => "Facsimile Number:",
"email" => "Email Address:",
"boe" => "Board of Education:",
"t_res" => "Teaching Resources:",
"t_res_desc" => "Not all schools have the same resources. When you find a lesson plan, you may need specific resources available in order to be able to teach that lesson plan. This section will ensure we know what will work and what wont work at your school.",
"t_books" => "Text Books:",
"c_room" => "School Has:",
"s_have" => "Students Have access to:",
"aDuaration_text" => "Activity Duration",
"aDuration_text_sub" => "time required to run this activity",
"aPax_text" =>"Maximum Participants",
"aPax_text_sub" => "the most you should attempt with",
"aPaxmin_text" => "Minimum Participants",
"aPaxmin_text_sub" => "the least number of students ",
"school_name_help" => "The name of your school. You do not need to put JHS, ES, Junior High School etc.",
"japanese_name_help" => "Japanese character name of your school.",
"boe_help" => "Board of Education that is responsible for the school.",
"school_name_help" => "The name of your school",
"school_name_p" => "Hokkaido Sapporo South High School",
"sel_level_help" => "Teaching level of this school",
"sel_color_help" => "The color you would like the classes of this school to appear as in the schedule.",
"sch_desc_help" => "You can write a brief text about your school.",
"add1_help" => "First line of your school's address.",
"add2_help" => "Second line of your schools address.",
"add3_help" => "Third line of your schools address.",
"pcode_help" => "Standard Japanese postal code.",
"city_help" => "The name of the city where your school is located.",
"prefecture_help" => "In which area is your school located?",
"telno_help" => "In case you need to contact the school in an emergency.",
"faxno_help" => "Some schools prefer to get things by fax. Supply a fax number for easy faxing.",
"email_help" => "This is an important address! It is where your lesson plans get sent to. You can also just specify your company email address here to have them sent to your branch office.",
"t_books_help" => "What text books does your school use? We can suggest lesson plans for you based on the books you use.",
"c_room_help" => "What resources does your school have for teaching English? Make sure you can teach the lesson plans  you find on Eigomonster",
"s_have_help" => "What resources do your students have access to?",
"sch_desc_p" => "Notes about the school.",
"japanese_name_p" => "e.g.北海道札幌南高等学校",
"save_as_new" => "save new",
"add_new" => "add new",
"save" => "save",
"add_new_warning"=>"your school has been saved. If you want to add a new school please use this button. Changing the data below will change the details for this school.",
"save_school" => "save school",
"add_new_school" => "add new school"

];



?>