<?php

//Content common to all pages

$messages = [
"page_title" => "アクティビティを追加",

"psel" => "選んでください",

"recent" => "最近に追加したアクティビティ",
"recent_sub" => "以下のアクティビティはどうですか？",
"suggested_activities" => "オズスメのアクティビティ",
"activity_name" => "アクティビティ名",
//Schools content

#schools dashboard page starts here
"activities" =>"自分のアクティビティ",

"activities_sub" =>"アクティビティセンターへようこそ. 以下は自分が保存されたアクティビティです. 編集したい場合は青いボタンをクリック。詳細を確認したいの方場合は学校名をクリック。",

#panels
"pan1_cnt_head" =>"アクティビティ",
"pan1_cnt_sub" =>"アカウントに追加した。",

"pan2_cnt_head" =>"レッスンプラン",
"pan2_cnt_sub" =>"アクティビティがない",
"psel" => "選んでください",
"button" =>"新しいアクティビティ",

#schools management page starts here.
"title" =>"クラスを管理する",

"update_head" =>"アクティビティを更新する",
"update_txt" =>"以下の詳細を更新してください。",
"update_head_sub" =>"",

"table_head" =>"アクティビティ",
"table_sub" =>"アクティビティセンターへようこそ. 以下は自分が保存されたアクティビティです. 編集したい場合は青いボタンをクリック。詳細を確認したいの方場合は学校名をクリック。新しい版を作成したい場合はまずコピーしてください。",

"create_head" =>"アクティビティを作成する",
"create_head_txt" =>"以下のフォームにアクティビティの詳細を入力してください。",
"create_head_sub" =>"",


#start headings for the form
"step1" =>"アクティビティ名",
"step2" =>"詳細",
"step3" =>"準備",
"step4" =>"教材",
"step5" =>"やり方説明",
"act_type" => "目標:",
"act_abil" => "スキルレベル:",
"act_name" =>"アクティビティ名",
"act_name_help" =>"このアクティビティに面白い名前をつけてください。",
"act_lang" =>"目標言語",
"act_lang_help" =>"このアクティビティに適した目標言語",
"act_summ" =>"概要",
"act_summ_help" =>"短い説明を入力してください",
"act_desc" =>"説明",
"act_desc_help" =>"詳しい説明を入力してください。",
"act_obj" =>"目標",
"act_obj_help" =>"このアクティビティの具体的な結果",
"act_time" =>"時間",
"act_time_help" =>"必要な時間を入力してください。",
"act_stu_min_help" =>"これよりも少なく、うまくいかない",
"act_stu_min" =>"最低学生数",
"act_stu_max" =>"最大学生数",
"act_stu_max_help" =>"Tこれ以上はうまくいかない",
"act_tags" =>"キーワード",
"act_tags_help" =>"",
"act_level" =>"発達段階",
"act_level_help" =>"学校の発達段階を入力してください。",
"act_grade" =>"学級",
"act_grade_help" =>"このアクティビティが最も適している学級。",
"act_team" =>"チームティチンッグ",
"act_team_help" =>"授業中のアクティビティ責任者。",
"act_text" =>"教科書",
"act_text_help" =>"このアクティビティで使用するテキストブック。",
"act_cres" =>"教室で必要なもの",
"act_cres_help" =>"このアクティビティに必要なリソース",
"act_sres" =>"生徒が必要なもの",
"act_sres_help" =>"生徒が用意するもの。",
"act_subject" =>"教科",
"act_subject_help" =>"このアクティビティの教科",
"act_other" =>"他に用意するもの",
"act_other_help" =>"特別な準備が必要な場合",
"act_user_subject" => "自分のカテゴリ",
"act_user_subject_help" => "自分の教科カテゴリーを選択してください",
"step1_sub" =>" - アクティビティの概要",
"step1_explain" =>"This is general information about the activity. This will appear in the searches and on your activities dashboard. The <strong>DESCRIPTION</strong> is for hints and tips. You will add detailed <strong>STEPS</strong> under the 5th section.",
"step2_sub" =>"",
"step2_explain" =>"These are important details for your activity. When you add the activity to a lesson plan, these will automatically be pulled through so that you know how many of everything you need to bring for example.",
"step3_sub" =>" - what you need to be successful.",
"step3_explain" =>"These are the resources that the classroom needs to have as well as the things the students need to bring. This will help you teaching partner know what to prepare for.",
"step4_sub" =>" - keep the learners engaged.",
"step4_explain" =>"These are the materials that are required to be brought by you or the HRT to teach the lesson. You should have added these by now to your profile. If not, you can go back and add them then come back and complete this activity.",
"step5_sub" =>" - a blow by blow guide of how to run this activity.",
"step5_explain" =>"This is the most important part of the activity. Break it down into simple, easy to understand steps so that someone you cannot speak to can read and understand. Keep it simple and be descriptive e.g. SAY: Stand up please. Hands up please. Let's Begin!",
"steps_adder" =>"ステップを追加",
"steps_adder_up" =>"ステップを更新",
"steps_adder_sub" =>"アクティビティにステップを追加",
"steps_adder_up_sub" =>"このステップを更新して",
"steps_adder_name" =>"ステップ名",
"steps_adder_name_place" =>"ステップ名",
"steps_adder_desc" =>"説明",
"steps_adder_place" =>"アクティビティにステップを追加",
"steps_adder_desc_place" =>"このステップのやり方や説明",
"steps_adder_say" =>"何をやります。",
"steps_adder_say_place" =>"What to say or do.",
"steps_adder_button" =>"追加",
"steps_sub" =>"教材を追加",
"steps_sub_sub" =>"教材を追加",
"steps_sub_explain" =>"To add a material, simply select it from this list and click the add material button.",
"steps_sub_button" =>"教材を追加",
"steps_sub_email" =>"電子メール",
"steps_header" =>"アクティビティ詳しい",
"steps_img_del" => "画像を削除",

"act_cmats" =>"現在教材",
"act_cmats_sub" =>"These are the materials you have added to this activity. You can add more as you need to. They will automatically be added to your lesson plan。",

"save_activity" => "アクティビティを保存",
"next" =>"次へ",
"previous" => "前へ",
"add_material" => "教材セットを追加",
"show" => "生徒に見せる",
"tell" => "生徒に伝える",
"step" => "ステップ情報",
"vital" => "必要",
"edit_step_text"=>"You can edit this step by changing the details below.",
"close"=>"閉じる",
"save"=>"保存",
"no_records_found"=>"結果がありません",
"no_objectives_added" => "",

"suggest" => "お進める",
"delete"=>"削除",
"reply"=>"返信",
"comment"=>"コメント",
"likes"=>"いいね",
"contributors"=>"投稿者",
"add_user"=>"ユーザーを追加",
"no_contributors"=>"投稿者はいません",
"objectives"=>"目標",
"no_steps_added"=>"ステップはありません",
"materials"=>"教材",
"no_materials_added"=>"教材はありません",
"add_plan" => "プランを作成",
"add_plan_sub" => "",
"select_plan" => "プランを選択",
"mod_close" => "閉じる",
"mod_save" => "保存",
"add_activity" => "アクティビティを追加",
"add_activity_sub" => "",
"select_activity" => "アクティビティを追加",
"add_material_sub" => "",
"select_material" => "教材を選択",
"sg_activity"=>"アクティビティ",
"sg_materials"=>"教材",
"sg_lessonplan"=>"レッスンプラン",
"plan_comment"=>"投稿",
"poster_placeholder"=>"いいアドバイスをお願いします！",
"save_class"=>"クラッスを保存",
"add_new_class"=>"クラスを作成",
"save_as_new" => "新件で保存",
"add_new" => "新規を作成",
"save" => "保存",
"school_level" => "発達段階",
"posted_status" => "投稿した",
"write_placeholder" => "コマンドのようにコメントする",
"suggested_label" => "お進めた",
"sug_plan_txt" => "レッスンプラン",
"sug_activity_txt" => "アクティビティ",
"sug_material_txt" => "教材",
"steps_type" => "ステップタイプ",
"steps_adder_say" => "何をやる又は言う",
"steps_adder_say_place" => "全員を立ってください",
"steps_crucial" => "大事",
"exit" => "戻る",
"print" => "印刷する"

]
?>
