<?php

//Content common to all pages

// app/messages/en.php
$messages = [

"dashboard" => "ダッシュボード",
"classes" => "学校",
"classes_sub" => "あなたが教える場所",
"no_plans" => "クラス",
"no_plans_sub" => "あなたのすべての学校で",
"activities" => "アクティビティ",
"activities_sub" => "保存された",
"lesson_plans" => "レッスンプラン",
"lesson_plans_sub" => "保存された",
"schedule" => "スケジュール",
"schedule_sub" => "今週のスケジュール",
"recent" => "最近追加された",
"recent_sub" => "最新のレッスンプラン",
"schools" => "自分の学校",
"schools_sub" => "教える場所",
"send" => "友人に招待状を送る",
"sendtext" => "あなたの友人のメールアドレスやその他の詳細を入力してください。",
"sendto" => "友達の名前:",
"sendtoemail" => "友人のメールアドレス:",
"message" => "メッセージ:",
"sendbutton" => "メールを送る",
"Close" => "閉じる",
"school_name" => "学校名",
"date" => "日付",
"theme" => "テーマ",
"plan_name" => "レッスンプラン名",
"description" => "説明",
"edit" => "編集",
"recent_notifications" => "最近の通知",
"recent_notifications_sub" => "忙しいですか？頑張っれ！",
"notification" => "通知",
"user_details" => "アカウント詳細",
"user_info" => "プロフィールの編集",
"profile_explanation" => "自分に付いて情報はこのページで編集ことが出来ます。",
"nickname" => "ニックネーム",
"nickname_help" => "システムで表示されたネーム",
"email" => "電子メール",
"email_help" => "通知に送られたメール",
"def_level" => "既定学校",
"def_level_help" => "以下のリストの中で一つを選ぶください。",
"def_subject" => "既定教科",
"def_subject_help" => "以下のリストの中で一つを選ぶください。",
"def_language_title" => "既定言語",
"def_language_help" => "以下のリストの中で一つを選ぶください。",
"old_pass" => "現在にパスワード",
"old_pass_help" => "現在のパスワードを入力してください",
"new_pass" => "新しいパスワード",
"new_pass_help" => "希望するパスワードを入力してください",
"con_pass" => "新しいパスワード",
"con_pass_help" => "確認の為にもう一度希望するパスワードを入力してください",
"register_asset" => "適用する",
"assets" => "承認コード",
"asset_pass_place" => "例: ea53b4cd78",
"asset_pass" => "コード",
"asset_pass_help" => "文科省対応プランの許可コードを入力してください。",
"asset_pass_help_warn" => "以下の文科省対応プランの許可コードは正しくではありません。もう一度やり直してください。",
"asset_pass_help_success" => "文科省対応プランの許可はプロフィールに追加されました。",
"cannot_update_settings" => "以下の設定は現在使われていません。",
"update_settings_info"=>"updating these settings will change the way the system interacts with you. <strong>Choosing not share your lesson plans means you will lose out on earning points for sharing knowledge.</strong>",
"def_share"=>"共有",
"def_share_help"=>"自分が作成した物のシステム全体共有状態。",
"show_public_help"=>"非公開プロフィルにしたい場合はオッフにしてください。",
"show_public"=>"非公開プロフィル",
"sys_emails"=>"システムメール",
"sys_emails_help" => "システムメールを受信したくない場合はオッフにしてください。",
"update_profile_btn" => "保存する",
"points" => "ポイント",
"earned" => "溜まった",
"materials" => "教材セット",
"donations" => "貢献",
"to_date" => "今まで",
"donate" => "貢献する",
"donate_again" => "再貢献する",
"teaching_level" => "学校",
"user_level" => "ユーザーステータス",
"defriend" => "除去する",
"pending" => "未決",
"confirm_request" => "確定",
"follow_confirmed" => "友達",
"follow_pending" => "友達を探す", 
"follow_requests" => "依頼", 
"edit_profile_picture" => "写真編集",
"edit_profile_picture_txt" => "素敵な写真を選択してください",
"edit_profile_picture_label" => "現在の写真",
"select_image" => "選ぶ",
"change_image" => "切り替え",
"remove_image" => "除去する",
"mod_close" => "閉じる",
"mod_save" => "save",
"mod_redeem" => "保存",
"please_consider_donating" => "we will try and keep eigomonster free! There are hard costs that we need to pay each month and some of these are covered through advertising. By contributing as little as JPY500 per month, you can help us keep eigomonster fed, watered and happy!",
"add_user" => "友達を追加",
"points" => "ポイント",
"redeem" => "ポイントの償還",
"points_to_redeem" => "ポイント",
"redeem_point_text" => "償還したいを100の倍数で入力してください",
"redeem_point" => "償還する",
"kakunin_kodo" => "承認コードを入力して下さい。",
"disk_space" => "ディスクスペース",



];

?>