<?php

//Content common to all pages

// app/messages/en.php
$messages = [
"page_title" => "スケジュール管理",
"your_schedule" => "スケジュル",
"your_schedule_sub" => "ここはスケジュル管理ページです。左側から日付までにクラスをドラッグしてください。月、週と日の詳細レベル切り替えことができます。",
"add_event" => "イベントを追加",
"drag_events" => "スケジュルにドラーグ",
"manage_class" => "クラスを管理する",
"manage_class_sub" => "このページで授業の詳細が書いてあります。はこちらのページからレッスンプランを追加することができます。",
"lesson_theme" => "レッスンテーマ",
"lesson_plan" => "レッスンプラン",
"lesson_plan_help" => "授業で使いたいレッスンプラン。",
"lesson_materials" => "教材",
"lesson_materials_help" => "授業で使いたい教材",
"activities" => "アクティビティ",
"activities_help" => "授業で使いたいアクティビティ",
"comment" => "コメント",
"comment_help" => "授業の感想またはコメントを入力してください。",
"delete_lesson" => "レッスンを削除する",
"update_lesson" => "レッスンを更新",
"missing_sch_resources" => "学校のリソースが足らない",
"missing_kids_resources" => "生徒用意する物が足りない",
"change_plan" => "プランを切り替えて",
"add_plan" => "プランを追加",
"add_user" => "ユーザーを追加",
"poster_placeholder" => "驚くばかりを追加する。。。",
"plan_comment" => "投稿する",
"add_activity" => "アクティビティを追加",
"add_material" => "教材を追加",
"add_lessonplan" => "プランを追加",
"psel" => "選ぶ",
"no_lesson_plan" => "この授業は追加されたレッスンプランはありません。追加可能性があります。",
"no_theme_assigned" => "授業にテーマ追加された場合は自動プラニングサポートがあります。",
"no_contributors" => "この授業に友達を招待しますとプラニングは必ずに簡単になるます。",
"no_theme_added" => "テーマはありません。レッスンプランテーマを入力してください。",
"add_activity_sub" => "自分のアクティビティズからこの授業に合うアクティビティをおすすめる。",
"mod_close" => "閉じて",
"mod_save" => "保存",
"suggested_label" => "おすすめ",
"sug_plan_txt" => "レッスンプラン",
"sug_activity_txt" => "アクティビティ",
"sug_material_txt" => "教材",
"search" => "検索",
"teach_rating" => "自分の評価",
"class_rating" => "子供の楽しみ",
"materials" => "教材",
"no_data_found" => "日程のデータは見つけられませんでした。スケジュールを更新してませんか？",
"click_to_change" => "期間を変更する。",
"rating_on_or_off" => "授業の評価を計算しない。",
"sch_tags" => "キーワード",
"sch_tags_help" => "キーワードで概要をします。",
"no_activities_added" => "この部分はアクティビティ追加されません。",
"add_plan_sub" => "レッスンプランを追加。",
"select_plan" => "プランを選択",
"lp_subj" => "教科",
"repeating_info" => "同じレッスンを毎週自動的に追加する。最大一年間制限があります。",
"frequency" => "周波数",
"weekly" => "毎週",
"biweekly" => "隔週",
"twoweeks" => "二週間",
"threemonth" => "3ヶ月",
"halfyear" => "半年",
"monthly" => "毎月",
"schedule_ahead" => "スケジュル予定",
"twoweeks" => "二週間",
"onemonth" => "１ヶ月",
"oneyear" => "1年間",
"occurences" => "回数",
"auto_schedule" => "自動スケジュル",
"planning"=>"プランニング",
"evaluation"=>"評価",
"occurs"=>"数",
"repeating_edit_info"=>"このシリーズを編集ことができますけど元に戻すことはできませんからご注意してください。",
"del_all"=>"シリーズを削除",
"lp_subj" => "教科",

];

?>