<?php


$messages =[
"page_title" => '学校管理',
"psel" => "選ぶ",
"save_as_new" => "新しく保存",
"save_school" => "保存する",
"add_new" => "学校を追加",
"add_new_school" => "学校を追加",
"add_new_warning" => "新しい学校を追加希望するのは緑バタンをクリックしてください。編集希望の場合は下にある青いバタンを押してください。",
"exit" => "戻る",
"dashboard" => "ダッシュボード",
"schools" => "自分の学校",
"schools_sub" => "学校管理センターへようこそ！以下は自分が保存された学校のリストです。編集したい方は青いボタンをクリック。詳細を確認したいの方は学校名をクリック。",
"schools_cnt_head" => "学校",
"schools_cnt_sub" => "アカウントに追加された",
"classes_cnt_head" => "クラス",
"classes_cnt_sub" => "学校全部の数。",
"button" => "学校を追加",
"title" => "学校情報を管理する",
"update_head" => "学校情報を更新するl",
"update_txt" => "学校の情報を更新してください。以下に入力し更新された情報はすぐにサイト全体で利用可能です。",
"update_head_sub" => "",
"create_head" => "学校を作成する",
"create_head_txt" => "学校の情報を以下にあるフォームで入力してください。たまに学校へ教材を無料で送ります。",
"create_head_sub" => "",
"overview" => "一般的な情報",
"address_details" => "住所",
"contact_details" => "連絡先",
"resources" => "教育機品",
"school_name" => "学校名 （ローマ字）",
"school_name_p" => "Monster's Elementary",
"japanese_name" => "学校名(漢字)",
"japanese_name_p" => "怪物小",
"sel_level" => "学校の発達段階",
"sel_color" => "スケジュールの色",
"sch_desc" => "学校説明",
"sch_desc_p" => "短い説明を入力してください[随意]",
"add_explain" => "エイゴモンスターは自分の学校に教材を直接送ることができます。",
"add1" => "住所",
"add2" => "地区",
"add3" => "その他",
"pcode" => "郵便番号",
"prefecture" => "都道府県名",
"city" => "市町村",
"next" => "次へ",
"previous" => "戻る",
"contact_details" => "連絡先の詳細",
"con_explain" => "オンラインストアで買ったものは学校に送ることができます。",
"telno" => "電話番号",
"faxno" => "ファックス番号",
"faxno_" => "ファックス番号を入力してください",
"email" => "メール",
"boe" => "教育委員会",
"t_res" => "教育機器",
"t_res_desc" => "学校ごとに機品が違います。自分の学校で使いたいレッスンプランが見つければ,この情報が便利になります。無い機品があればシステムでお知らせします。",
"t_books" => "教科書",
"c_room" => "学校にあるもの",
"s_have" => "生徒が持ってるもの",

];



?>
