<?php

//Content common to all pages

$messages = [
"page_title" => "アクティビティを追加",

"psel" => "選んでください",

"recent" => "最近に追加したアクティビティ",
"recent_sub" => "以下のアクティビティはどうですか？",
"suggested_activities" => "オズスメのアクティビティ",
"activity_name" => "アクティビティ名",
//Schools content

#schools dashboard page starts here
"activities" =>"自分のアクティビティ",

"activities_sub" =>"アクティビティセンターへようこそ. 以下は自分が保存されたアクティビティです. 編集したい場合は青いボタンをクリック。詳細を確認したいの方場合は学校名をクリック。",

#panels
"pan1_cnt_head" =>"アクティビティ",
"pan1_cnt_sub" =>"アカウントに追加した。",

"pan2_cnt_head" =>"レッスンプラン",
"pan2_cnt_sub" =>"アクティビティがない",
"psel" => "選んでください",
"button" =>"新しいアクティビティ",

#schools management page starts here.
"title" =>"Manage Classes",

"update_head" =>"アクティビティを更新する",
"update_txt" =>"以下の詳細を更新してください。",
"update_head_sub" =>"<small> keepin' it <strong>real</strong>, like it should be.</small>",

"table_head" =>"アクティビティ",
"table_sub" =>"アクティビティセンターへようこそ. 以下は自分が保存されたアクティビティです. 編集したい場合は青いボタンをクリック。詳細を確認したいの方場合は学校名をクリック。新しい版を作成したい場合はまずコピーしてください。",

"create_head" =>"アクティビティを作成する",
"create_head_txt" =>"以下のフォームにアクティビティの詳細を入力してください。",
"create_head_sub" =>"<small> make sure the monstar are <strong>need</strong> enageged </small>",


#start headings for the form
"step1" =>"アクティビティ名",
"step2" =>"詳細",
"step3" =>"準備",
"step4" =>"教材",
"step5" =>"やり方説明",
"act_type" => "目標:",
"act_abil" => "スキルレベル:",
"act_name" =>"アクティビティ名",
"act_name_help" =>"このアクティビティに面白い名前をつけてください。",
"act_lang" =>"目標言語",
"act_lang_help" =>"このアクティビティに適した目標言語",
"act_summ" =>"概要",
"act_summ_help" =>"短い説明を入力してください",
"act_desc" =>"説明",
"act_desc_help" =>"詳しい説明を入力してください。",
"act_obj" =>"目標",
"act_obj_help" =>"このアクティビティの具体的な結果",
"act_time" =>"時間",
"act_time_help" =>"必要な時間を入力してください。",
"act_stu_min_help" =>"これよりも少なく、うまくいかない",
"act_stu_min" =>"最低学生数",
"act_stu_max" =>"最大学生数",
"act_stu_max_help" =>"Tこれ以上はうまくいかない",
"act_tags" =>"タッグ",
"act_tags_help" =>"Tags to help you associate this activity with lesson plans and materials",
"act_level" =>"発達段階",
"act_level_help" =>"学校の発達段階を入力してください。",
"act_grade" =>"学級",
"act_grade_help" =>"このアクティビティが最も適している学級。",
"act_team" =>"チームティチンッグ",
"act_team_help" =>"授業中のアクティビティ責任者。",
"act_text" =>"教科書",
"act_text_help" =>"このアクティビティで使用するテキストブック。",
"act_cres" =>"教室で必要なもの",
"act_cres_help" =>"このアクティビティに必要なリソース",
"act_sres" =>"生徒が必要なもの",
"act_sres_help" =>"生徒が用意するもの。",
"act_subject" =>"教科",
"act_subject_help" =>"このアクティビティの教科",
"act_other" =>"他に用意するもの",
"act_other_help" =>"特別な準備が必要な場合",
"step1_sub" =>" - アクティビティの概要",
"step1_explain" =>"This is general information about the activity. This will appear in the searches and on your activities dashboard. The <strong>DESCRIPTION</strong> is for hints and tips. You will add detailed <strong>STEPS</strong> under the 5th section.",
"step2_sub" =>" - it is all in the detail.",
"step2_explain" =>"These are important details for your activity. When you add the activity to a lesson plan, these will automatically be pulled through so that you know how many of everything you need to bring for example.",
"step3_sub" =>" - what you need to be successful.",
"step3_explain" =>"These are the resources that the classroom needs to have as well as the things the students need to bring. This will help you teaching partner know what to prepare for.",
"step4_sub" =>" - keep the learners engaged.",
"step4_explain" =>"These are the materials that are required to be brought by you or the HRT to teach the lesson. You should have added these by now to your profile. If not, you can go back and add them then come back and complete this activity.",
"step5_sub" =>" - a blow by blow guide of how to run this activity.",
"step5_explain" =>"This is the most important part of the activity. Break it down into simple, easy to understand steps so that someone you cannot speak to can read and understand. Keep it simple and be descriptive e.g. SAY: Stand up please. Hands up please. Let's Begin!",
"steps_adder" =>"Add steps",
"steps_adder_up" =>"Update steps",
"steps_adder_sub" =>"Add a new step to this activity.",
"steps_adder_up_sub" =>"Update this step in this activity.",
"steps_adder_name" =>"Step Name",
"steps_adder_name_place" =>"Step Name",
"steps_adder_desc" =>"Description",
"steps_adder_place" =>"Add steps to this activity.",
"steps_adder_desc_place" =>"What needs to be done?",
"steps_adder_button" =>"Add Step",
"steps_sub" =>"Add Material",
"steps_sub_sub" =>"Add Material",
"steps_sub_explain" =>"To add a material, simply select it from this list and click the add material button.",
"steps_sub_button" =>"Add Material",
"steps_sub_email" =>"Email",
"steps_header" =>"Activity details",

"act_cmats" =>"Current Materials",
"act_cmats_sub" =>"These are the materials you have added to this activity. You can add more as you need to. They will automatically be added to your lesson plan",

"save_activity" => "save activity",
"next" =>"Next",
"previous" => "Previous",
"add_material" => "add material",
"show" => "Show the students",
"tell" => "Tell the students",
"step" => "Step information",
"vital" => "vital",
"edit_step_text"=>"You can edit this step by changing the details below.",
"close"=>"close",
"save"=>"save",
"no_records_found"=>" no records found",
"no_objectives_added" => "no objectives added",

"suggest" => "suggest",
"delete"=>"reply",
"reply"=>"reply",
"comment"=>"comment",
"likes"=>"like",
"contributors"=>"contributors",
"add_user"=>"add user",
"no_contributors"=>"no contributors added",
"objectives"=>"objectives",
"no_steps_added"=>"no steps added",
"materials"=>"materials",
"no_materials_added"=>"no_materials added",
"add_plan" => "add a lesson plan",
"add_plan_sub" => "you can add a lesson plan to this discussion to help guide it.",
"select_plan" => "select a plan",
"mod_close" => "close",
"mod_save" => "save",
"add_activity" => "add activity",
"add_activity_sub" => "you can add an activity to this discussion to help guide it.",
"select_activity" => "select activity",
"add_material" => "add material",
"add_material_sub" => "you can add a material set to this discussion to help guide it.",
"select_material" => "select material",
"sg_activity"=>"activity",
"sg_materials"=>"material",
"sg_lessonplan"=>"lesson plan",
"plan_comment"=>"post",
"poster_placeholder"=>"give some great advice...",
"save_class"=>"Save Class",
"add_new_class"=>"add new class",
"save_as_new" => "save new",
"add_new" => "add new",
"save" => "save",
"school_level" => "school level",
"posted_status" => "posted",
"write_placeholder" => "comment like a commando",
"suggested_label" => "suggested",
"sug_plan_txt" => "lesson plan",
"sug_activity_txt" => "activity",
"sug_material_txt" => "material",
"steps_type" => "Step Type",
"steps_adder_say" => "What to do or say"


]
?>
