<?php


$messages = [

"schedule_home" => "スケジュール",
"plans_home" => "レッスンプラン",
"profile_home" => "プロフィール",
"mark_read" => "既読にする",
"new_notifications" => "新通知",
"view_all" => "すべて表示",
"language" => "言語",
"english" => "english",
"japanese" => "japanese",
"logout" => "ログアウト",
"ago" => "前",
"dashboard" => "ダッシュボード",
"settings" => "設定",
"my_profile" => "私のプロフィール",
"my_schools" => "私の学校",
"my_classes" => "私のクラス",
"invite_monsters" => "友達を招待",
"teaching" => "教育",
"create_materials" => "教材を作成",
"manage_materials" => "教材を管理",
"manage_activities" => "教育活動を管理",
"manage_lesson_plans" => "授業内容を管理",
"manage_schedule" => "日課を管理",
"view_timeline" => "タイムラインを表示する",
"inspiration" => "吸気",
"find_lesson_plans" => "プランを探す",
"find_activities" => "プランを探す",
"check_curricula" => "教育活動を探す",
"material_shop" => "material shop",
"mailbox" => "mailbox",
"new" => "新しい",
"psel" => "選んでください",
"search" => "探索。。。",
"coming_soon" => "近日公開",
"schedule" => "自分の日課",
"textbooks" => "教科書",
"mailbox" => "受信トレイ",
"schedule" => "スケジュール",
"schedule_sub" => "今週のスケジュール",
"recent_notifications" => "最近の通知",
"recent_notifications_sub" => "忙しいですか？頑張っれ！",
"no_important_notifications" => "新しい通知はありません",
"school_name" => "学校名",
"date" => "日付",
"theme" => "テーマ",
"recent" => "最近追加された",
"recent_sub" => "最新のレッスンプラン",
"view" => "見る",


];