<?php

// app/messages/en.php
$messages = [
	"psel" => "選んでください",
	"page_title"    => "教材を作成",
	"associate_textbook" => "教科書を関連付ける",
	"avaiable_words" => "利用可能な単語",
	"manage_options" => "オプションを管理する",
	"structure" => "作文",
    "act_text"      => "教科書",
	"txt_page" => "関連するページを選択してください",
    "add_words" => "単語を追加する",
	"no_words_found" => "このページには単語が見つかりません",
	"gen_words" => "単語を作成する",
    "clear_words"    => "すべてクリア",
	"generator_name" => "ジェネレータ名",
	"type" => "種類",
	"view" => "見る",
	"gen_subj" => "教科",
	"gen_name"     => "名",
	"gen_name_help" => "教材ジェネレータの名前を入力してください。",
	"gen_head"     => "見出し",
	"gen_head_help"     => "教材ジェネレータの見出しを入力してください。",
	"gen_subtext"     => "小見出し",
	"gen_subtext_help"     => "教材ジェネレータの小見出しを入力してください。",
	"show_name"     => "名前ラベルテキスト",
	"show_name_help"     => "生徒が名前を書く場所のテキスト。",
	"show_class"     => "クラス名ラベルテキスト",
	"show_class_help"     => "生徒がクラス名を書く場所のテキスト。",
	"show_date"     => "日付ラベルテキスト",
	"show_date_help"     => "生徒が日付を書く場所かのテキスト。",
	"show_name_check"     => "名前ボックス",
	"show_name_check_help"     => "名前ボックスを表示する?",
	"show_class_check" => "クラス名ボックス",
	"show_class_check_help" => "クラス名ボックスを表示する?",
	"show_date_check" => "日付ボックス",
	"show_date_check_help" => "日付ボックスを表示する?",
	"gen_desc"     => "説明",
	"gen_desc_help" => "他のユーザが簡単にこの教材の使い方を理解しての説明。",
	"save_and_print" => "保存と印刷。まずは以上のオプションを保存してください。",
	"view" => "表示する",
	"download" => "PDFダウンロード",
	"save_as_new" => "新しいものとして保存",
	"save" => "保存する",
	"add_new" => "新しく追加する",
	"save_options" => "オプションを保存",
	"remove_vowels" => "母音を隠す",
	"quiz" => "クイズ",
	"guide" => "ガイド",
	"trace" => "トレース",
	"shuffle_vowels" => "母音をシャッフル",
	"shuffle_word" => "単語シャッフル",
	"subtext_word" => "説明テキスト",
	"save_block" => "単語を保存する",
	"activities" => "保存した教材ジェネレータ",
	"activities_sub" => "以下はあなたが作成した教材ジェネレータのリストです。",
	"recent" => "最近追加された",
	"recent_sub" => "自分の最新保存した教材ジェネレータ。",
	"suggested_generators" => "おすすめ教材ジェネレータ。",
	"gen_words_help" => "自分がほしい単語を入力してください。",
	"act_text_help" => "教科書を選んでください。"
	
	

	
];


