// JavaScript Document

var res = {
    activityTourTitle : "アクティビティ",
    activityTourContent : "追加されたされたアクティビティは以下の一覧表で表示されいます。",
	activityAddTitle : "新規を追加",
	activityAddContent : "このバタンをクリックすると新しいアクティビティを追加が出来ます。",
	activityManageTitle : "アクティビティを編集",
	activityManageContent : "アクティビティを作成又は編集希望のかたはこのフォームを使ってください。",
	activitySaveTitle : "アクティビティを保存する",
	activitySaveContent : "編集が終わったら必ず「保存する」をクリックしてください。",
	ACT_COPY_DIALOGUE : "コピー: Ctrl+C / Cmd + C, Enter",
	ACT_DEL_DIALOGUE : 'この行を削除しますか？',
	ACT_STEP_WARN : "ステップ名と説明が必要です。",
	ACT_SAVE :"アクティビティ保存されました。",
	ACT_SAVE_STATUS :"保存状態",
	ACT_SAVE_ERROR :"障害が発生しています。もう一度やり直して下さい。",
	ACT_SAVE_ERROR_2 :"サーバー障害が発生しています。",
	TOAST_BEFORE :"今回は　<strong>",
	TOAST_AFTER :"</strong> ポイントが貯まりました。",
	ACT_POINTS : "ポイント!",
	ACT_REP_COMM:"了解! 返事は追加された.",
	ACT_REP_COMM_STATUS: "返事",
	ACT_REP_COMM_ERROR: "エラーが発生されました。もう一度返事してください。",
	ACT_PLAN_STATUS :"日程更新",
	ACT_PLAN :"レッスン編集完了しました。",
	ACT_PLAN_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_COMM_STATUS : "アクティビティにコメント",
	ACT_COMM : "了解！ 追加されました。",
	ACT_COMM_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_LIKE : "「いいね！",
	ACT_LIKE_ERROR :"障害が発生しています。もう一度やり直して下さい。" ,
	ACT_LIKE_STATUS : "いいね」しました。",
	ACT_COM_DEL : "コメントが削除されました。",
	ACT_COM_DEL_STATUS : "削除状態",
	ACT_COM_DEL_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_COM_DEL_CON :"本当に削除しますか？",
	ACT_ADD_CON : "寄稿者が追加されました。" ,
	ACT_ADD_CON_STATUS : "寄稿者",
	ACT_ADD_CON_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_MAT_ADD :"アクティビティに教材が追加されました。",
	ACT_MAT_ADD_STATUS : "教材を追加",
	ACT_MAT_ADD_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_MAT_DEL : "アクティビティから教材が削除されました。",
	ACT_MAT_DEL_STATUS : "教材の削除状態",
	ACT_MAT_DEL_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_STEP_ADD : "アクティビティにステップが追加されました。",
	ACT_STEP_ADD_STATUS : "ステップを追加 ",
	ACT_STEP_ADD_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_STEP_EDIT : "ステップが編集されました。",
	ACT_STEP_EDIT_STATUS :"ステップ編集",
	ACT_STEP_EDIT_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_STEP_DEL : "ステップが削除されました。",
	ACT_STEP_DEL_STATUS :"ステップ削除",
	ACT_STEP_DEL_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	ACT_DEL_DIALOGUE: "このステップを削除しまうか？"
};


