// JavaScript Document

var res = {
    INS_LIKE_SAVED : "Your like has been registered.",
	INS_LIKE_STATUS: "Like Status",
	INS_LIKE_ERROR : "There was an error processing your request.",
    INS_PTS_EARN: "Points Earned",
	INS_SAVE_STATUS : "Save Status",	
	INS_TOAST_BEFORE :"You have earned <strong>",
	INS_TOAST_AFTER : "</strong> points",
	INS_PLAN_ERROR : "There was an error copying your lesson plan. Try again please." ,
	INS_PLAN_SENT : "Bon Voyage! Lesson plan has been sent.",
	INS_PLAN_STATUS : "Send Lesson Plan",
	INS_ACT_ERROR : "There was an error copying your activity. Try again please." ,
	INS_ACT_SENT : "Bon Voyage! Activity has been sent.",
	INS_ACT_STATUS : "Send Activity",
	INS_MAT_ERROR : "There was an error copying your material. Try again please." ,
	INS_MAT_SENT : "Bon Voyage! Material has been sent.",
	INS_MAT_STATUS : "Send Material",
	INS_INV_SENT : "Bon Voyage! Your invitation has been sent.",
	INS_INV_ERROR : "There was an error sending your inviation. Try again please.",
	INS_INV_STATUS : "Send Invitation",
    INS_PTS_EARN: "Points Earned",
	INS_COMM_PLAN_SAVE : "Roger That! Comment has been added.",
	INS_COMM_PLAN_ERROR : "There was an error adding your comment to this lesson plan. Try again please",
	INS_COMM_PLAN_STATUS : "Lesson Plan Comment",
	INS_PLAN_COPY_SAVE :"Your plan has been copied",
	INS_PLAN_COPY_ERROR : "There was an error processing your request",
	INS_PLAN_COPY_STATUS :"Copy Status",
	INS_COPY_TEXT : "Copy to clipboard: Ctrl+C / Cmd + C, Enter",
	INS_MAT_COPY_SAVE :"Your naterial set has been copied",
	INS_MAT_COPY_ERROR : "There was an error processing your request",
	INS_MAT_COPY_STATUS :"Copy Status",
	INS_ACT_COPY_SAVE :"Your activity has been copied",
	INS_ACT_COPY_ERROR : "There was an error processing your request",
	INS_ACT_COPY_STATUS :"Copy Status",

};

