// JavaScript Document

var res = {
    materialTourTitle : "教材",
    materialTourContent : "教材を追加すると、ここに表示されます。",
	materialAddTitle : "追加",
	materialAddContent : "自分のプロフィールに教材を追加する。",
	materialSearchTitle : "検索",
    materialSearchContent : "他の先生が作った教材を見に行く。",
	materialFormTitle : "教材情報",
    materialFormContent : "教材を管理することが出来ます。",
	materialManageTitle : "教材を管理する",
    materialManageContent : "ここから教材の詳細を編集が出来ます。",
	materialSaveTitle : "教材を保存する",
    materialSaveContent : "ここをクリックすると、入力された情報が保存されます。",
	MAT_SAVED : "教材が保存されました。",
	MAT_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	MAT_DATA_ERROR : "障害が発生しています。もう一度やり直して下さい。",
    MAT_PTS_EARN: "獲得ポイント",
	MAT_SAVE_STATUS : "保存状況",	
	MAT_TOAST_BEFORE :　"<strong>",
	MAT_TOAST_AFTER : "</strong> 獲得しました。",
	MAT_DEL_CONFIRM: "本当に削除しますか？",
	MAT_DELETE: "削除しました。",
	MAT_DELETE_ERROR: "障害が発生しています。もう一度やり直して下さい。",
	MAT_DELETE_STATUS: "削除状況",
	MAT_REP_COMM:"了解！ 追加されました。",
	MAT_REP_COMM_STATUS: "コメントに返事する",
	MAT_REP_COMM_ERROR: "障害が発生しています。もう一度やり直して下さい。",
	MAT_PLAN_STATUS :"教材更新",
	MAT_PLAN :"教材セットが更新されました。",
	MAT_PLAN_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	MAT_COMM_STATUS : "コメントを受け付けました",
	MAT_COMM : "コメントが反映されました。",
	MAT_COMM_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	MAT_LIKE : "いいね！",
	MAT_LIKE_ERROR :"障害が発生しています。もう一度やり直して下さい。" ,
	MAT_LIKE_STATUS : "「いいね」しました。",
	MAT_COM_DEL : "コメントが削除されました。",
	MAT_COM_DEL_STATUS : "削除状態",
	MAT_COM_DEL_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	MAT_COM_DEL_CON :"本当に削除しますか？",
	MAT_ADD_CON : "寄稿者が追加されました。" ,
	MAT_ADD_CON_STATUS : "寄稿者",
	MAT_ADD_CON_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	
	
	

};

