// JavaScript Document

var res = {
    planTourTitle : "レッスン計画",
    planTourContent : "制作した資料を管理できます。",
	planAddTitle : "レッスン計画を追加",
	planAddContent : "ここで新しい資料が製作できます。",
	planManageTitle : "概要欄入力ページ",
	planManageContent : "各項目に必要事項を入力し、「次へ」を押して下さい。",
	planSaveTitle : "レッスン計画を保存",
	planSaveContent : "「保存」を押して終了して下さい。",
	PLAN_COPY_DIALOGUE : "クリップボードにコピー: Ctrl+C / Cmd + C, Enter",
	PLAN_DEL_DIALOGUE : 'この行を消しますか？',
	PLAN_NUMBERS_ONLY :"数字で入力して下さい。",
	PLAN_STEP_WARN : "項目名と説明を入力して下さい。",
	PLAN_SAVE :"レッスン計画を保存しました。",
	PLAN_SAVE_STATUS :"保存",
	PLAN_SAVE_ERROR :"障害が発生しています。もう一度やり直して下さい。",
	PLAN_SAVE_ERROR_2 :"障害が発生しています。もう一度やり直して下さい。",
	TOAST_BEFORE :"<strong>　",
	TOAST_AFTER :"</strong> 獲得しました。",
	PLAN_POINTS : "ポイント！",
	PLAN_REP_COMM:"了解！追加されました。",
	PLAN_REP_COMM_STATUS: "コメントに返事する",
	PLAN_REP_COMM_ERROR: "障害が発生しています。もう一度やり直して下さい。",
	PLAN_PLAN_STATUS :"スケジュールの更新",
	PLAN_PLAN :"スケジュールの更新が完了しました！",
	PLAN_PLAN_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	PLAN_COMM_STATUS : "コメントが反映されました。",
	PLAN_COMM : "了解！追加されました。",
	PLAN_COMM_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	PLAN_LIKE : "いいね！",
	PLAN_LIKE_ERROR :"障害が発生しています。もう一度やり直して下さい。" ,
	PLAN_LIKE_STATUS : "「いいね」しました。",
	PLAN_COM_DEL : "コメントが削除されました。",
	PLAN_COM_DEL_STATUS : "削除状況",
	PLAN_COM_DEL_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	PLAN_COM_DEL_CON :"コメントを本当に削除しますか？",
	PLAN_ADD_CON : "コンタクトが追加されました。" ,
	PLAN_ADD_CON_STATUS : "寄稿者",
	PLAN_ADD_CON_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	PLAN_ACT_ADD :"レッスン計画に新しいアクティビティが追加されました。",
	PLAN_ACT_ADD_STATUS : "アクティビティを追加",
	PLAN_ACT_ADD_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	PLAN_ACT_DEL : "アクティビティを消去しました。",
	PLAN_ACT_DEL_STATUS : "アクティビティを消去",
	PLAN_ACT_DEL_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	PLAN_SECT : "レッスン計画の一部を更新しました。",
	PLAN_SECT_STATUS : "更新",
	PLAN_SECT_ERROR : "障害が発生しています。もう一度やり直して下さい。",
	PLAN_SECT_ERROR_2 : "障害が発生しています。もう一度やり直して下さい。"

};

