// JavaScript Document

var res = {
    activityTourTitle : "Activities",
    activityTourContent : "As you add activities to you profile they will appear here.",
	activityAddTitle : "Add New",
	activityAddContent : "Clicking this  button will allow you to add new activities",
	activityManageTitle : "Manage Activity",
	activityManageContent : "This form will allow you to create or update activities. Fill in as much information as you can.",
	activitySaveTitle : "Save Activity",
	activitySaveContent : "When you are done, remember to hit save.",
	ACT_COPY_DIALOGUE : "Copy to clipboard: Ctrl+C / Cmd + C, Enter",
	ACT_DEL_DIALOGUE : 'Do you want to delete this row?',
	ACT_STEP_WARN : "You must specify a Step Name and Description",
	ACT_SAVE :"Your activity set has been saved",
	ACT_SAVE_STATUS :"Save Activity",
	ACT_SAVE_ERROR :"There was an error processing your request",
	ACT_SAVE_ERROR_2 :"Your data was not sent to the server",
	TOAST_BEFORE :"you have earned <strong>",
	TOAST_AFTER :"</strong> points",
	ACT_POINTS : "Points!",
	ACT_REP_COMM:"Roger That! Reply has been added.",
	ACT_REP_COMM_STATUS: "Reply to Comment",
	ACT_REP_COMM_ERROR: "There was an error adding your reply. Try again please.",
	ACT_PLAN_STATUS :"Schedule Update",
	ACT_PLAN :"Your lesson has been updated successfully!",
	ACT_PLAN_ERROR : "There was an error updating your lesson. Try again please.",
	ACT_COMM_STATUS : "Comment on Activity",
	ACT_COMM : "Roger That! Comment has been added.",
	ACT_COMM_ERROR : "There was an error adding your comment. Try again please.",
	ACT_LIKE : "Like Status",
	ACT_LIKE_ERROR :"There was an error processing your request" ,
	ACT_LIKE_STATUS : "Your like has been saved",
	ACT_COM_DEL : "Your comment has been deleted.",
	ACT_COM_DEL_STATUS : "Delete Status",
	ACT_COM_DEL_ERROR : "There was an error processing your request.",
	ACT_COM_DEL_CON :"Do you want to delete this comment?",
	ACT_ADD_CON : "Your contact has been added" ,
	ACT_ADD_CON_STATUS : "Add Contact Status",
	ACT_ADD_CON_ERROR : "There was an error processing your request.",
	ACT_MAT_ADD :"New Material added to activity",
	ACT_MAT_ADD_STATUS : "Add Material",
	ACT_MAT_ADD_ERROR : "There was an error adding your material. Try again please.",
	ACT_MAT_DEL : "New Material deleted from activity",
	ACT_MAT_DEL_STATUS : "Material Deletion Status",
	ACT_MAT_DEL_ERROR : "There was an error deleting your material. Try again please",
	ACT_STEP_ADD : "New Step added to activity",
	ACT_STEP_ADD_STATUS : "Add Step ",
	ACT_STEP_ADD_ERROR : "There was an error adding your step. Try again please",
	ACT_STEP_EDIT : "Step edited",
	ACT_STEP_EDIT_STATUS :"Edit Step",
	ACT_STEP_EDIT_ERROR : "There was an error editing your step. Try again please.",
	ACT_STEP_DEL : "Step deleted",
	ACT_STEP_DEL_STATUS :"Delete Step",
	ACT_STEP_DEL_ERROR : "There was an error deleting your step. Try again please.",
	ACT_DEL_DIALOGUE: "Do you really want to delete this step?"
};


