// JavaScript Document

var res = {
    planTourTitle : "Lesson Plans",
    planTourContent : "As you add lesson plans to you profile they will appear here. This is also when you copy lesson plans.",
	planAddTitle : "Add New",
	planAddContent : "Clicking this  button will allow you to add new lesson plans",
	planManageTitle : "Manage Plans",
	planManageContent : "This form will allow you to create or update lesson plans. Fill in as much information as you can.",
	planSaveTitle : "Save Plan",
	planSaveContent : "When you are done, remember to hit save.",
	PLAN_COPY_DIALOGUE : "Copy to clipboard: Ctrl+C / Cmd + C, Enter",
	PLAN_DEL_DIALOGUE : 'Do you want to delete this row?',
	PLAN_NUMBERS_ONLY :"Please enter numbers only.",
	PLAN_STEP_WARN : "You must specify a Step Name and Description",
	PLAN_SAVE :"Your lesson plan has been saved",
	PLAN_SAVE_STATUS :"Save Plan",
	PLAN_SAVE_ERROR :"There was an error processing your request",
	PLAN_SAVE_ERROR_2 :"Your data was not sent to the server",
	TOAST_BEFORE :"you have earned <strong>",
	TOAST_AFTER :"</strong> points",
	PLAN_POINTS : "Points!",
	PLAN_REP_COMM:"Roger That! Reply has been added.",
	PLAN_REP_COMM_STATUS: "Reply to Comment",
	PLAN_REP_COMM_ERROR: "There was an error adding your reply. Try again please.",
	PLAN_PLAN_STATUS :"Schedule Update",
	PLAN_PLAN :"Your lesson has been updated successfully!",
	PLAN_PLAN_ERROR : "There was an error updating your lesson. Try again please.",
	PLAN_COMM_STATUS : "Comment on Activity",
	PLAN_COMM : "Roger That! Comment has been added.",
	PLAN_COMM_ERROR : "There was an error adding your comment. Try again please.",
	PLAN_LIKE : "Like Status",
	PLAN_LIKE_ERROR :"There was an error processing your request" ,
	PLAN_LIKE_STATUS : "Your like has been saved",
	PLAN_COM_DEL : "Your comment has been deleted.",
	PLAN_COM_DEL_STATUS : "Delete Status",
	PLAN_COM_DEL_ERROR : "There was an error processing your request.",
	PLAN_COM_DEL_CON :"Do you want to delete this comment?",
	PLAN_ADD_CON : "Your contact has been added" ,
	PLAN_ADD_CON_STATUS : "Add Contact Status",
	PLAN_ADD_CON_ERROR : "There was an error processing your request.",
	PLAN_ACT_ADD :"New Activity added to this section of the plan.",
	PLAN_ACT_ADD_STATUS : "Add Activity",
	PLAN_ACT_ADD_ERROR : "There was an error adding your activity. Try again please.",
	PLAN_ACT_DEL : "Actvity deleted from plan",
	PLAN_ACT_DEL_STATUS : "Activity Deletion",
	PLAN_ACT_DEL_ERROR : "There was an error deleting your activity. Try again please",
	PLAN_SECT : "Your section has been updated",
	PLAN_SECT_STATUS : "Section Update",
	PLAN_SECT_ERROR : "Your data was not sent to the server",
	PLAN_SECT_ERROR_2 : "There was an error processing your request"

};

