<?php


$messages = [

"on" => "on",
"off" => "off",
"delete" => "delete",
"exit" => "exit",
"add_new" => "add new",
"save" => "save",
"psel" => "Please select...",
"save_as_new" => "save as new",
"schedule_home" => "schedule",
"plans_home" => "lesson plans",
"profile_home" => "profile",
"mark_read" => "mark as read",
"new_notifications" => "new notifications",
"view_all" => "view all notifications",
"language" => "language",
"english" => "english",
"japanese" => "日本語",
"logout" => "log out",
"ago" => "ago",
"dashboard" => "dashboard",
"settings" => "settings",
"no_perms" => "You do not have the required permissions to view this page. Please head to your profile and input the auth codes to allow you to view this page. You can ask your school administrator for the codes.",
"manage_learning" => "manage learning",
"my_subjects" => "my subjects",
"recent_notifications" => "notifications",
"recent_notifications_sub" => "when it happens, you'll be the first to know!",
"my_profile" => "my profile",
"my_schools" => "my schools",
"my_classes" => "my classes",
"invite_monsters" => "invite monsters",
"teaching" => "teaching",
"manage_materials" => "manage materials",
"create_materials" => "generate materials",
"manage_activities" => "manage activities",
"manage_lesson_plans" => "manage lesson plans",
"manage_schedule" => "manage schedule",
"view_timeline" => "view timeline",
"inspiration" => "inspiration",
"find_lesson_plans" => "find lesson plans",
"find_lesson_plan_sets" => "find lesson sets",
"find_activities" => "find activities",
"check_curricula" => "check curricula",
"material_shop" => "material shop",
"mailbox" => "mailbox",
"new" => "new",
"psel" => "Please select...",
"search" => "search for something",
"coming_soon" => "coming soon",
"contributors" => "contributors",
"textbooks" => "textbooks",
"nokori" => NULL,
"maximum" => NULL,
"lesson_plans_head" => NULL,
"ind_current"=> NULL,
"jp_counter" => NULL,
"jp_contr" => NULL,
//translations for limit bans

"add_materials" => "Add Materials",
"add_materials_first_text" => "<p>You will need at least one set of materials to be able to create an activity. Please add a set of materials then add an activity.</p><p>If you are adding an activity that you feel does not need materials you can proceed anyway.</p>",
"general_dependency" => "Add Items",
"please_create_objects" => "Great lesson plans are detailed lesson plans. Please consider adding some activities and materials to your profile so that you can create a lesson plan that is easy to follow. If you are stuck for ideas, why not search the database to find and copy activities to your profile for free.",
"add_activity" => "Add Activity",
"search_activity" => "search activities",
"search_plans" => "search plans",
"proceed_anyway" => "proceed",
"textbooks" => "browse textbooks",
"send" => "invite a Friend",
"sendtext" => "you can invite a friend to become a monster by sending them an email! Simply fill out the form below and hit send. we'll take care of the rest.",
"sendto" => "to name:",
"sendtoemail" => "to email:",
"message" => "message:",
"sendbutton" => "send email",
"Close" => "close",
"page_description_generic" => "eigomonster is a virtual teaching assistant designed to empower teahers to provide incredible learning environments for their teachers. automate your teaching life today!",
"add_schools" => "Add Schools",
"add_schools_first_text" => "You need to add a school first.<br><br>Classes are always assigned to schools so that they can easily be tracked in the schedule. Please add at least one school first. This can be something as simple as <strong>My House</strong>. ",
"close" => "close",
"add_school" => "add a school",
"add_classes" => NULL,
"add_classes_first_text" => "You need to add a class first. <br><br>Your schedule is where you will spend most of your time. By adding classes we will be able to send you <strong>customised lessons</strong> based on who you are teaching.",
"add_class" => "add a class",
"profile_setup_missing" => "Your profile is not complete so we cannot show you suggested lesson plans. Please setup your profile to see suggested plans that relate to your teaching subject and grade level.",
"comment_plan_like_msg" => "Your lesson plan has a new like.",
"comment_act_like_msg" => "Your activity has a new like.",
"comment_mat_like_msg" => "Your material has a new like.",
"comment_follow_like_msg" => "You have a new follow request.",
"comment_mat_msg" => "You material has a new comment.",
"comment_mat" => "Material comment",
"comment_act_msg" => "Your activity has a new comment.",
"comment_act" => "Activity comment",
"comment_sch_msg" => "Your lesson has a new comment.",
"comment_sch" => "Lesson comment",
"translate_this" => "翻訳を見る",
"resource_consumption" => "Resource Consumption",
"lesson_plans" => "Lesson Plans",
"disk_space" => NULL,
"remaining" => "remaining",
"so_far_plan" => "created",
"so_far_act" => "saved",
"so_far_mat" => "stored",
"for_your_plan" => "for your current plan",
"activities" => "Activities",
"materials" => "Materials",
"donate" => "Please consider contributing to cover your portion of the costs required to keep this site up and running and pay for future development. So far", //number of donaters here
"donate_average" => "people have contributed this month. The current average contribution is about",
"donate_please" => "Becoming a contributor will remove all adverts and lift your limits. Contributions are handled securely via PayPal.",
"new" => "new",
"give" => "donate",
"used" => "used so far",
"donate_blue" => "This site is provided free to all users. Please be careful what you are uploading to the system so that we can ensure it remains free with limited advertisers.",

"lesson_act_head" => NULL,
"lesson_mat_head"=> NULL,
"lesson_data_head" => NULL,
"available_words" => "available　words",






];