<?php

$messages = [

"delta_trackers" => "Delta Trackers",
"delta_trackers_sub" => "Delta Trackers allow you to keep track of your students progress in aquiring new skills and then provide them with sufficicent scaffolding to assist their development. Delta Trackers are linked to generators so you should ideally have at least one generator setup before trying to setup a new delta tracker.",
"statistics" => "Statistics",
"statistics_sub" => "Key statistics are displayed here to help you make better decisions in the classroom.",
"key_stats" => "Key Statistics",
"page_title" => "Manage Delta",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",
"" => "",


]

?>