<?php

//Content common to all pages

// app/messages/en.php
$messages = [

"dashboard" => "dashboard",
"classes" => "schools",
"classes_sub" => "you teach at.",
"no_plans" => "classes",
"no_plans_sub" => "at all of your schools",
"activities" => "activities",
"activities_sub" => "on your profile",
"lesson_plans" => "lesson plans",
"lesson_plans_sub" => "you have created",
"schedule" => "your schedule",
"schedule_sub" => "what you are teaching in the next few days.",
"recent" => "recently added",
"recent_sub" => "these are the latest lesson plans in the database.",
"schools" => "your schools",
"schools_sub" => "these are the schools you teach at.",
"send" => "invite a Friend",
"sendtext" => "you can invite a friend to become a monster by sending them an email! Simply fill out the form below and hit send. we'll take care of the rest.",
"sendto" => "to name:",
"sendtoemail" => "to email:",
"message" => "message:",
"sendbutton" => "send email",
"Close" => "close",
"school_name" => "school name",
"date" => "date",
"theme" => "theme",
"plan_name" => "plan name",
"description" => "description",
"edit" => "edit",
"user_details" => "your details",
"user_info" => "about you",
"profile_explanation" => "these are the details that relate to your account on the system. You can update these as you need to and they will affect the way the system interacts with you.",
"nickname" => "nickname",
"nickname_help" => "this is the name that will appear on the system.",
"email" => "email",
"email_help" => "this is email address to which we will send notifications.",
"def_level" => "default level",
"def_level_help" => "this is the teaching level that you teach most often.",
"def_subject" => "default subject",
"def_subject_help" => "this is the subject you teach most often.",
"def_language_title" => "default language",
"def_language_help" => "the language you would like the system to display",
"old_pass" => "old password",
"old_pass_help" => "your old password",
"new_pass" => "new password",
"new_pass_help" => "new old password",
"con_pass" => "new password",
"con_pass_help" => "new old password",
"register_asset" => "Apply",
"assets" => "codes",
"asset_pass" => "Asset code",
"asset_pass_place" => "e.g.: ea53b4cd78",
"asset_pass_help" => "Please enter the code that will allow you to view lesson plans that are not publically available",
"asset_pass_help_warn" => "The code you entered does not seem to be correct. Please check it and try and again.",
"asset_pass_help_success" => "Permission successfully applied to your profile.",
"cannot_update_settings" => "these settings can only be updated if you have reached 'kocho' status or if you have made a contribution of JPY500 or more. These contributions will help to pay for running costs and upgrades to the system.'",
"update_settings_info"=>"updating these settings will change the way the system interacts with you. <strong>Choosing not share your lesson plans means you will lose out on earning points for sharing knowledge.</strong>",
"def_share"=>"share",
"def_share_help"=>"the default setting for sharing materials, activities and lesson plans.",
"show_public"=>"hide or show your profile in the public member gallery. Hiding will not allow you to contribute to discussions.",
"show_public"=>"public profile",
"sys_emails"=>"system emails",
"sys_emails_help" => "choose if you want to receive system emails. You may find it gets rather quiet without this being checked.",
"update_profile_btn" => "update profile",
"points" => "points",
"earned" => "earned",
"donations" => "donations",
"to_date" => "to date",
"donate" => "donate",
"donate_again" => "donate again",
"teaching_level" => "teaching level",
"user_level" => "user status",
"defriend" => "remove",
"pending" => "pending",
"confirm_request" => "confirm",
"follow_confirmed" => "your friends",
"follow_pending" => "find friends", 
"follow_requests" => "follow requests", 
"edit_profile_picture" => "edit profile picture",
"edit_profile_picture_txt" => "you can edit your profile picture. Please try and use something that shows your face. Helps people find you easily.",
"edit_profile_picture_label" => "current picture",
"select_image" => "select",
"change_image" => "change",
"remove_image" => "remove",
"mod_close" => "close",
"mod_save" => "save",
"mod_redeem" => "redeem",
"please_consider_donating" => "we will try and keep eigomonster free! There are hard costs that we need to pay each month and some of these are covered through advertising. By contributing as little as JPY500 per month, you can help us keep eigomonster fed, watered and happy!",
"add_user" => "add friend",
"points" => "points",
"redeem" => "redeem",
"points_to_redeem" => "Points to redeem",
"redeem_point_text" => "Please enter the number of points you would like to redeem in multiples of 100.",
"redeem_point" => "Redeem Points",
"kakunin_kodo" => "please enter your code...",
"disk_space" => "disk space",







];

?>